DROP TABLE IF EXISTS "address" CASCADE;
DROP TABLE IF EXISTS "video" CASCADE;
DROP TABLE IF EXISTS "photo" CASCADE;
DROP TABLE IF EXISTS "review" CASCADE;
DROP TABLE IF EXISTS "category" CASCADE;
DROP TABLE IF EXISTS "variant" CASCADE;
DROP TABLE IF EXISTS "product_detail" CASCADE;
DROP TABLE IF EXISTS "product" CASCADE;
DROP TABLE IF EXISTS "favorite" CASCADE;
DROP TABLE IF EXISTS "voucher" CASCADE;
DROP TABLE IF EXISTS "promotion" CASCADE;
DROP TABLE IF EXISTS "transaction" CASCADE;
DROP TABLE IF EXISTS "sealabs_pay" CASCADE;
DROP TABLE IF EXISTS "wallet_history" CASCADE;
DROP TABLE IF EXISTS "wallet_history" CASCADE;
DROP TABLE IF EXISTS "wallet" CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS "order_item" CASCADE;
DROP TABLE IF EXISTS "cart_item" CASCADE;
DROP TABLE IF EXISTS "product_courier_whitelist" CASCADE;
DROP TABLE IF EXISTS "shop_courier" CASCADE;
DROP TABLE IF EXISTS "shop" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
DROP
EXTENSION IF EXISTS "uuid-ossp" CASCADE;
DROP
EXTENSION IF EXISTS pg_trgm CASCADE;
